backend:
  name: git-gateway
  branch: main

media_folder: "images" # where uploaded images will go
public_folder: "/images"

collections:
  - name: "updates"
    label: "Latest Updates"
    folder: "_updates"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "content", widget: "text" }

  - name: "gallery"
    label: "Gallery"
    folder: "images"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Caption", name: "caption", widget: "string" }
