backend:
  name: github
  repo: musee-00/st-kidane-mehret-church  # your repo name
  branch: main  # branch to update

media_folder: "images"      # where uploaded images will go
public_folder: "images"

collections:
  - name: "updates"
    label: "Latest Updates"
    folder: "_updates"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "content", widget: "text" }

  - name: "gallery"
    label: "Gallery Images"
    folder: "_gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Caption", name: "caption", widget: "string" }
